### ISSUE TITLE
Project grouping

### ISSUE THREAD

**Issue by aureq** [deskypus/app#4]
**Is your feature request related to a problem? Please describe.**

For users with many projects, it can be hard to find the correct project.

**Describe the solution you'd like**

Consider arbitrary project grouping, with collapsible elements so it's easy to navigate through long list of projects.

**Comment by praneetloke** [comment]
It would also be nice to group projects by the org they belong to.

**Comment by praneetloke** [comment]
I am working on this feature. For the first implementation, the grouping will be manual. Users can create groups and organize projects in those groups.

**Comment by praneetloke** [comment]
I've written about the development and the progress I've made so far in my weeknotes. Check it out at https://weeknotes.cloudysky.software/archive/june-2023/

**Comment by praneetloke** [comment]
This is now available in preview form with [v0.1.2](https://github.com/deskypus/app/releases/v0.1.2).
